baseURL = "https://antoniomatier.netlify.app/"
languageCode = "en-us"
summaryLength = 30
[[menu.main]]
name = "Login"
weight = 9
[[menu.main]]
name = "Concierge"
weight = 7
[[menu.main]]
name = "Home Value Request"
parent = "Client Relations"
url = "/home-value-request"
weight = 1
[[menu.main]]
name = "Client Relations"
weight = 6
[[menu.main]]
name = "Northern California Multi-Million Dollar Estates"
parent = "Estate Homes"
weight = 2
[[menu.main]]
name = "Southern California Multi-Million Dollar Estates"
parent = "Estate Homes"
weight = 1
[[menu.main]]
name = "Estate Homes"
weight = 5
[[menu.main]]
name = "Southern California Homes and Condos Priced from 501k to 1M"
parent = "Buyers & Sellers"
weight = 3
[[menu.main]]
name = "Southern California Million Dollar Leases"
parent = "Luxury Homes"
weight = 4
[[menu.main]]
name = "Southern California Million Dollar Homes"
parent = "Luxury Homes"
weight = 3
[[menu.main]]
name = "Northern California Million Dollar Leases"
parent = "Luxury Homes"
weight = 2
[[menu.main]]
name = "Northern California Million Dollar Homes"
parent = "Luxury Homes"
weight = 1
[[menu.main]]
name = "Luxury Homes"
weight = 3
[[menu.main]]
name = "Southern California Homes and Condos Priced from 50k to 500k"
parent = "New Home Search"
weight = 9
[[menu.main]]
name = "Northern California Condos and Homes Priced from 501k to 1M"
parent = "New Home Search"
weight = 8
[[menu.main]]
name = "Northern California Condos and Homes Priced from 50k to 500k"
parent = "New Home Search"
weight = 7
[[menu.main]]
name = "Open Homes"
parent = "New Home Search"
url = "http://www.idxhome.com/openhomes/"
weight = 6
[[menu.main]]
name = "Sold Listings"
parent = "New Home Search"
weight = 5
[[menu.main]]
name = "Email Alerts"
parent = "New Home Search"
url = "http://www.idxhome.com/organizer/emailAlerts/"
weight = 4
[[menu.main]]
name = "Advanced Search"
parent = "New Home Search"
url = "http://www.idxhome.com/listing/search/advanced//13"
weight = 3
[[menu.main]]
name = "Search"
parent = "New Home Search"
url = "http://www.idxhome.com/homesearch/"
weight = 2
[[menu.main]]
name = "New Home Search"
parent = "New Home Search"
url = "https://www.idxhome.com/featured/"
weight = 1
[[menu.main]]
name = "New Home Search"
weight = 2
[[menu.main]]
name = "Valuation Request"
parent = "Buyers & Sellers"
url = "http://www.idxhome.com/valuation/"
weight = 2
[[menu.main]]
name = "Property Organizer"
parent = "Buyers & Sellers"
url = "http://www.idxhome.com/organizer/login/"
weight = 1
[[menu.main]]
name = "Buyers & Sellers"
weight = 4
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[taxonomies]
category = "categories"
tag = "tags"